name: Build and Push Docker Image

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-2
  ECR_REPOSITORY: blog-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::991467040640:role/GitHubActions-ECR-Role
          aws-region: ap-south-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest .

      - name: Push Docker image
      
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest